/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/about': RouteRecordInfo<
      '/about',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/archives': RouteRecordInfo<
      '/archives',
      '/archives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/autumn-thoughts': RouteRecordInfo<
      '/posts/autumn-thoughts',
      '/posts/autumn-thoughts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/hello': RouteRecordInfo<
      '/posts/hello',
      '/posts/hello',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/moonlight': RouteRecordInfo<
      '/posts/moonlight',
      '/posts/moonlight',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/snow-coding': RouteRecordInfo<
      '/posts/snow-coding',
      '/posts/snow-coding',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/spring-rain': RouteRecordInfo<
      '/posts/spring-rain',
      '/posts/spring-rain',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/tech-shuimo': RouteRecordInfo<
      '/posts/tech-shuimo',
      '/posts/tech-shuimo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'pages/index.md': {
      routes:
        | '/'
      views:
        | never
    }
    '../node_modules/.pnpm/valaxy@0.26.13_@babel+parser@7.29.2_@types+markdown-it@14.1.2_@types+node@25.6.0_@vue+c_61c35e8c552d76d52908b761f1c69cac/node_modules/valaxy/client/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'pages/about.md': {
      routes:
        | '/about'
      views:
        | never
    }
    '../theme/pages/archives.vue': {
      routes:
        | '/archives'
      views:
        | never
    }
    'pages/posts/autumn-thoughts.md': {
      routes:
        | '/posts/autumn-thoughts'
      views:
        | never
    }
    'pages/posts/hello.md': {
      routes:
        | '/posts/hello'
      views:
        | never
    }
    'pages/posts/moonlight.md': {
      routes:
        | '/posts/moonlight'
      views:
        | never
    }
    'pages/posts/snow-coding.md': {
      routes:
        | '/posts/snow-coding'
      views:
        | never
    }
    'pages/posts/spring-rain.md': {
      routes:
        | '/posts/spring-rain'
      views:
        | never
    }
    'pages/posts/tech-shuimo.md': {
      routes:
        | '/posts/tech-shuimo'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
